replicaCount: 2

image:
  repository: registry.digitalocean.com/chat-service/chat-api
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: chat.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

envVars:
  DATABASE_URL: ""
  REDIS_URL: ""
  PORT: "3001"
  HOST: "0.0.0.0"