apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chat-service.fullname" . }}
  labels:
    {{- include "chat-service.labels" . | nindent 4 }}
imagePullSecrets:
  - name: {{ include "chat-service.fullname" . }}-registry
---
# registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat-service.fullname" . }}-registry
  labels:
    {{- include "chat-service.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}