apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-service-promtail
  labels:
    {{- include "chat-service.labels" . | nindent 4 }}
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://{{ .Values.monitoring.loki.url }}/loki/api/v1/push
    scrape_configs:
      - job_name: chat-service-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: chat-service
              __path__: /var/log/*.log
        pipeline_stages:
          - json:
              expressions:
                timestamp: time
                level: level
                message: msg